name: Go

on:
  push:
    branches: [ test-own-repo ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    environment: b2
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Test
      run: go test -v ./...
      env:
        ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
        APPLICATION_KEY: ${{ secrets.APPLICATION_KEY }}
